### PR TITLE
General improvements - Build with gradle-java-plugin, cleanup task input warnings, & helpers for Aql

### PR DESCRIPTION
**Pull request by Emilio-Pega**
## Infrastructure changes:
build the plugin using the [java-gradle-plugin](https://docs.gradle.org/current/userguide/java_gradle_plugin.html) plugin as suggested by gradle, giving us access to additional checks

## Task warning cleanup
Now that we use java-gradle-plugin, we can run the `check` task and get a list of task warnings about bad/missing input & output annotations.  I have cleaned up the warnings and adjusted the build script so that the greadle build wil lfail if new ones are introduced

## Per-task configuration of `artifactoryRest` settings
A common use case is that I want some of my REST commands to go to different artifactory URLs with different credentials.  Previously, this was difficult to setup or configure.  Now, each task has a nested `artifactoryRest` property (values default to the ones in project.artifactoryRest) which can be used to override the settings if needed.

## Get artifacts from an Aql task
For SetProperties, DeleteArtifact, and CopyArtifact tasks, there is a very common usage pattern which goes like:

1. Run an Aql task
2. Run SetProperties, DeleteArtifact, or CopyArtifact tasks using the results of the Aql task

Examples:
* Find all artifacts created yesterday and delete them
* Find all artifacts with a specific path and copy them
* Find all artifacts in a specific repo and set the properties

In order to make this common pattern easier to configure (and remove bunches of boilerplate for consumer), the 3 tasks have a new helper method called artifactsFromAql(...)

### CODE REVIEW

**Comment by cdancy** [comment]
@Emilio-Pega LGTM. Anything else you want to do here or are you ready to merge and get a new release?

**Comment by Emilio-Pega** [comment]
Nothing else :) ready for release, hopefully won't take 3mo to adopt this time

**Comment by cdancy** [comment]
@Emilio-Pega I'm not judging ;)

Give me 10 minutes or so and I'll get `v1.1.0` out.

**Comment by cdancy** [comment]
@Emilio-Pega `v1.1.0` should be good to go.

**Pull request merged**
