### PR TITLE
Add a retry mechanism to the SetProperties task

### PR DESCRIPTION
**Pull request by Emilio-Pega**
Add a simple retry mechanism to the SetProperties task

### CODE REVIEW

**Comment by Emilio-Pega** [comment]
Builds were failing with 
```
Installing oraclejdk8
$ export JAVA_HOME=~/oraclejdk8
$ export PATH="$JAVA_HOME/bin:$PATH"
$ ~/bin/install-jdk.sh --target "/home/travis/oraclejdk8" --workspace "/home/travis/.cache/install-jdk" --feature "8" --license "BCL"
Ignoring license option: BCL -- using GPLv2+CE by default
install-jdk.sh 2019-07-17
Expected feature release number in range of 9 to 14, but got: 8
The command "~/bin/install-jdk.sh --target "/home/travis/oraclejdk8" --workspace "/home/travis/.cache/install-jdk" --feature "8" --license "BCL"" failed and exited with 3 during
```

So changed travis.yaml to use `dist: trusty` as suggested by https://travis-ci.community/t/error-installing-oraclejdk8-expected-feature-release-number-in-range-of-9-to-14-but-got-8/3766/10

**Comment by cdancy** [comment]
@Emilio-Pega so the change, on the face of it, is good it's just very targeted and not as generic as I would like. But ... and as I understand your use-case the time to do so may be a bit much to invest in doing that. So I'll take this in, and kick a new point release, but will probably look into providing a more generic solution in the next week or so, and then ripping this out, when I have the time. Just don't have it at the moment so you're getting your way :)

**Comment by Emilio-Pega** [comment]
@cdancy Ok, that is about what I figured you'd say :P, out of curiosity, what is you opinion o nthe way I did the unit tests?  I didn't see a good pattern, so I just re-used the one I have used for our internal plugins

**Comment by cdancy** [comment]
@Emilio-Pega oh the unit test is fine and considering there is no current pattern in place it's a good start to get something going.

**Comment by cdancy** [comment]
@Emilio-Pega version `0.0.17` should be available and good to go.

**Pull request merged**
