### PR TITLE
Bring the plugin into the gradle 5+ era with the gradle Property API

### PR DESCRIPTION
**Pull request by Emilio-Pega**
Modernize the tasks and extension to use the gradle Property APIs for input values.

**THIS IS A BREAKING CHANGE**

As part of doing this I created a lot of the missing unit tests for the tasks.

### CODE REVIEW

**Comment by Emilio-Pega** [comment]
@cdancy Hey Chris, what do you think of this?  Its not something required by any work I'm doing, but it feels weird to stil be using raw closures at this point...

**Comment by cdancy** [comment]
@Emilio-Pega preparing `1.0.0` release now...

**Comment by cdancy** [comment]
Going to be a bit as the upload to bintray failed due to changes in the plugin/gradle/etc.

**Comment by cdancy** [comment]
@Emilio-Pega `v1.0.0` has been released.

**Comment by Emilio-Pega** [comment]
Nice, thanks @cdancy i'm going to spin it into our plugins *after* the march 31st gradle 6 upgrade

**Pull request merged**
